# Exception

## Throw exception


```cs
namespace ExceptionExample
{
    class CustomException : Exception
    {
        public CustomException(string message)
        {
        }
    }
    internal class Program
    {
        static void Main(string[] args)
        {
            try
            {
                throw new CustomException("Custom exception in TestThrow()");
            }
            catch (CustomException ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

```cs
using System;
using System.IO;

namespace Exceptions
{
    public class CatchOrder
    {
        public static void Main()
        {
            try
            {
                using (var sw = new StreamWriter("./test.txt"))
                {
                    sw.WriteLine("Hello");
                }
                using (var sr = new StreamReader("./test.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
                using (var sr = new StreamReader("./test1.txt"))
                {
                    Console.WriteLine(sr.ReadLine());
                }
            }
            // Put the more specific exceptions first.
            catch (DirectoryNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            catch (FileNotFoundException ex)
            {
                Console.WriteLine(ex);
            }
            // Put the least specific exception last.
            catch (IOException ex)
            {
                Console.WriteLine(ex);
            }
            Console.WriteLine("Done");
        }
    }
}
```